server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: TRAINING-SERVICE
          uri: lb://TRAINING-SERVICE
          predicates:
            - Path=/exercise/**, /training/**

        - id: STATISTIC-SERVICE
          uri: lb://STATISTIC-SERVICE
          predicates:
            - Path=/statistic/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/